# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\48560330q\PycharmProjects\meso_2D\2D_0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 10, 401, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_resultados = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_resultados.setEnabled(False)
        self.lb_resultados.setObjectName("lb_resultados")
        self.verticalLayout_2.addWidget(self.lb_resultados)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setEnabled(False)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lb_estructura = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_estructura.setEnabled(False)
        self.lb_estructura.setObjectName("lb_estructura")
        self.verticalLayout_2.addWidget(self.lb_estructura)
        self.gv_visor = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.gv_visor.setEnabled(False)
        self.gv_visor.setObjectName("gv_visor")
        self.verticalLayout_2.addWidget(self.gv_visor)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 386, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 7, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.le_dmax_ptos = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_dmax_ptos.setEnabled(False)
        self.le_dmax_ptos.setObjectName("le_dmax_ptos")
        self.gridLayout.addWidget(self.le_dmax_ptos, 7, 3, 1, 1)
        self.lb_dmin_ptos = QtWidgets.QLabel(self.layoutWidget)
        self.lb_dmin_ptos.setEnabled(False)
        self.lb_dmin_ptos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_dmin_ptos.setObjectName("lb_dmin_ptos")
        self.gridLayout.addWidget(self.lb_dmin_ptos, 8, 2, 1, 1)
        self.lb_dmax_ptos = QtWidgets.QLabel(self.layoutWidget)
        self.lb_dmax_ptos.setEnabled(False)
        self.lb_dmax_ptos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_dmax_ptos.setObjectName("lb_dmax_ptos")
        self.gridLayout.addWidget(self.lb_dmax_ptos, 8, 3, 1, 1)
        self.le_Pptos = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_Pptos.setEnabled(False)
        self.le_Pptos.setObjectName("le_Pptos")
        self.gridLayout.addWidget(self.le_Pptos, 7, 4, 1, 1)
        self.lb_Pptos = QtWidgets.QLabel(self.layoutWidget)
        self.lb_Pptos.setEnabled(False)
        self.lb_Pptos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_Pptos.setObjectName("lb_Pptos")
        self.gridLayout.addWidget(self.lb_Pptos, 8, 4, 1, 1)
        self.le_x = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_x.setObjectName("le_x")
        self.gridLayout.addWidget(self.le_x, 2, 2, 1, 1)
        self.lb_x = QtWidgets.QLabel(self.layoutWidget)
        self.lb_x.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_x.setObjectName("lb_x")
        self.gridLayout.addWidget(self.lb_x, 3, 2, 1, 1)
        self.lb_y = QtWidgets.QLabel(self.layoutWidget)
        self.lb_y.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_y.setObjectName("lb_y")
        self.gridLayout.addWidget(self.lb_y, 3, 3, 1, 1)
        self.le_y = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_y.setObjectName("le_y")
        self.gridLayout.addWidget(self.le_y, 2, 3, 1, 1)
        self.lb_dmin = QtWidgets.QLabel(self.layoutWidget)
        self.lb_dmin.setEnabled(False)
        self.lb_dmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_dmin.setObjectName("lb_dmin")
        self.gridLayout.addWidget(self.lb_dmin, 6, 2, 1, 1)
        self.lb_dmax = QtWidgets.QLabel(self.layoutWidget)
        self.lb_dmax.setEnabled(False)
        self.lb_dmax.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_dmax.setObjectName("lb_dmax")
        self.gridLayout.addWidget(self.lb_dmax, 6, 3, 1, 1)
        self.le_Pporos = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_Pporos.setEnabled(False)
        self.le_Pporos.setObjectName("le_Pporos")
        self.gridLayout.addWidget(self.le_Pporos, 5, 4, 1, 1)
        self.lb_dimensiones = QtWidgets.QLabel(self.layoutWidget)
        self.lb_dimensiones.setObjectName("lb_dimensiones")
        self.gridLayout.addWidget(self.lb_dimensiones, 2, 1, 1, 1)
        self.lb_Pporos = QtWidgets.QLabel(self.layoutWidget)
        self.lb_Pporos.setEnabled(False)
        self.lb_Pporos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_Pporos.setObjectName("lb_Pporos")
        self.gridLayout.addWidget(self.lb_Pporos, 6, 4, 1, 1)
        self.le_dmax = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_dmax.setEnabled(False)
        self.le_dmax.setObjectName("le_dmax")
        self.gridLayout.addWidget(self.le_dmax, 5, 3, 1, 1)
        self.lb_poros = QtWidgets.QLabel(self.layoutWidget)
        self.lb_poros.setEnabled(False)
        self.lb_poros.setObjectName("lb_poros")
        self.gridLayout.addWidget(self.lb_poros, 5, 1, 1, 1)
        self.cb_puntos = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_puntos.setText("")
        self.cb_puntos.setObjectName("cb_puntos")
        self.gridLayout.addWidget(self.cb_puntos, 7, 0, 1, 1)
        self.le_dmin_ptos = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_dmin_ptos.setEnabled(False)
        self.le_dmin_ptos.setObjectName("le_dmin_ptos")
        self.gridLayout.addWidget(self.le_dmin_ptos, 7, 2, 1, 1)
        self.le_dmin = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_dmin.setEnabled(False)
        self.le_dmin.setObjectName("le_dmin")
        self.gridLayout.addWidget(self.le_dmin, 5, 2, 1, 1)
        self.cb_poros = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_poros.setText("")
        self.cb_poros.setObjectName("cb_poros")
        self.gridLayout.addWidget(self.cb_poros, 5, 0, 1, 1)
        self.lb_puntos = QtWidgets.QLabel(self.layoutWidget)
        self.lb_puntos.setEnabled(False)
        self.lb_puntos.setObjectName("lb_puntos")
        self.gridLayout.addWidget(self.lb_puntos, 7, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lb_semilla = QtWidgets.QLabel(self.layoutWidget)
        self.lb_semilla.setEnabled(False)
        self.lb_semilla.setObjectName("lb_semilla")
        self.gridLayout.addWidget(self.lb_semilla, 0, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 1, 0, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 8, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 13, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 11, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 12, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_anyadir = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_anyadir.setObjectName("pb_anyadir")
        self.horizontalLayout.addWidget(self.pb_anyadir)
        self.pb_eliminar = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_eliminar.setObjectName("pb_eliminar")
        self.horizontalLayout.addWidget(self.pb_eliminar)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 1)
        self.pb_ejecutar = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_ejecutar.setObjectName("pb_ejecutar")
        self.gridLayout_2.addWidget(self.pb_ejecutar, 10, 0, 1, 1)
        self.lb_dosif = QtWidgets.QLabel(self.layoutWidget)
        self.lb_dosif.setObjectName("lb_dosif")
        self.gridLayout_2.addWidget(self.lb_dosif, 4, 0, 1, 1)
        self.tabla_dosif = QtWidgets.QTableWidget(self.layoutWidget)
        self.tabla_dosif.setObjectName("tabla_dosif")
        self.tabla_dosif.setColumnCount(0)
        self.tabla_dosif.setRowCount(0)
        self.gridLayout_2.addWidget(self.tabla_dosif, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.a_Nuevo = QtWidgets.QAction(MainWindow)
        self.a_Nuevo.setEnabled(True)
        self.a_Nuevo.setObjectName("a_Nuevo")
        self.a_Abrir = QtWidgets.QAction(MainWindow)
        self.a_Abrir.setObjectName("a_Abrir")
        self.a_GuardarP = QtWidgets.QAction(MainWindow)
        self.a_GuardarP.setEnabled(False)
        self.a_GuardarP.setObjectName("a_GuardarP")
        self.a_Informe = QtWidgets.QAction(MainWindow)
        self.a_Informe.setEnabled(False)
        self.a_Informe.setObjectName("a_Informe")
        self.a_Salir = QtWidgets.QAction(MainWindow)
        self.a_Salir.setObjectName("a_Salir")
        self.a_Estructura = QtWidgets.QAction(MainWindow)
        self.a_Estructura.setEnabled(False)
        self.a_Estructura.setObjectName("a_Estructura")
        self.a_Dosif = QtWidgets.QAction(MainWindow)
        self.a_Dosif.setEnabled(False)
        self.a_Dosif.setObjectName("a_Dosif")
        self.a_Tutorial = QtWidgets.QAction(MainWindow)
        self.a_Tutorial.setObjectName("a_Tutorial")
        self.a_Acerca = QtWidgets.QAction(MainWindow)
        self.a_Acerca.setObjectName("a_Acerca")
        self.a_Semilla = QtWidgets.QAction(MainWindow)
        self.a_Semilla.setEnabled(False)
        self.a_Semilla.setObjectName("a_Semilla")
        self.a_Ejecutar = QtWidgets.QAction(MainWindow)
        self.a_Ejecutar.setEnabled(False)
        self.a_Ejecutar.setObjectName("a_Ejecutar")
        self.menuArchivo.addAction(self.a_Nuevo)
        self.menuArchivo.addAction(self.a_Abrir)
        self.menuArchivo.addAction(self.a_GuardarP)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.a_Estructura)
        self.menuArchivo.addAction(self.a_Informe)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.a_Salir)
        self.menuAyuda.addAction(self.a_Tutorial)
        self.menuAyuda.addAction(self.a_Acerca)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_resultados.setText(_translate("MainWindow", "Resultados"))
        self.lb_estructura.setText(_translate("MainWindow", "Estructura"))
        self.lb_dmin_ptos.setText(_translate("MainWindow", "Dmin"))
        self.lb_dmax_ptos.setText(_translate("MainWindow", "Dmax"))
        self.lb_Pptos.setText(_translate("MainWindow", "%"))
        self.lb_x.setText(_translate("MainWindow", "X"))
        self.lb_y.setText(_translate("MainWindow", "Y"))
        self.lb_dmin.setText(_translate("MainWindow", "Dmin"))
        self.lb_dmax.setText(_translate("MainWindow", "Dmax"))
        self.lb_dimensiones.setText(_translate("MainWindow", "Dimensiones de la probeta"))
        self.lb_Pporos.setText(_translate("MainWindow", "%"))
        self.lb_poros.setText(_translate("MainWindow", "Poros"))
        self.lb_puntos.setText(_translate("MainWindow", "Puntos reactivos"))
        self.lb_semilla.setText(_translate("MainWindow", "Semilla"))
        self.pb_anyadir.setText(_translate("MainWindow", "Añadir"))
        self.pb_eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.pb_ejecutar.setText(_translate("MainWindow", "Ejecutar"))
        self.lb_dosif.setText(_translate("MainWindow", "Dosificación"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.a_Nuevo.setText(_translate("MainWindow", "Nuevo Proyecto"))
        self.a_Abrir.setText(_translate("MainWindow", "Abrir Proyecto"))
        self.a_GuardarP.setText(_translate("MainWindow", "Guardar Proyecto"))
        self.a_Informe.setText(_translate("MainWindow", "Generar Informe"))
        self.a_Salir.setText(_translate("MainWindow", "Salir"))
        self.a_Estructura.setText(_translate("MainWindow", "Guardar Estructura"))
        self.a_Dosif.setText(_translate("MainWindow", "Dosificación"))
        self.a_Tutorial.setText(_translate("MainWindow", "Tutorial"))
        self.a_Acerca.setText(_translate("MainWindow", "Acerca de"))
        self.a_Semilla.setText(_translate("MainWindow", "Semilla"))
        self.a_Ejecutar.setText(_translate("MainWindow", "Ejecutar"))

