# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_GV.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_GV(object):
    def setupUi(self, Dialog_GV):
        Dialog_GV.setObjectName("Dialog_GV")
        Dialog_GV.resize(605, 472)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_GV)
        self.gridLayout.setObjectName("gridLayout")
        # self.graphicsView = QtWidgets.QGraphicsView(Dialog_GV)
        # self.graphicsView.setObjectName("graphicsView")
        # self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Dialog_GV)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_GV)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)

        self.retranslateUi(Dialog_GV)
        QtCore.QMetaObject.connectSlotsByName(Dialog_GV)

    def retranslateUi(self, Dialog_GV):
        _translate = QtCore.QCoreApplication.translate
        Dialog_GV.setWindowTitle(_translate("Dialog_GV", "Structure Viewer"))
        self.pushButton.setText(_translate("Dialog_GV", "Save"))
        self.pushButton_2.setText(_translate("Dialog_GV", "Close"))
